name: NuGet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Clean
      run: dotnet clean
    - name: NuGet clear cache
      run: nuget locals all -clear

    - name: Restore tools
      run: dotnet tool restore
    #- name: Check format
    #  run: dotnet format --verify-no-changes

    - name: Restore dependencies
      run: dotnet restore
    - name: Check dependencies for deprecated packages
      run: dotnet list package --deprecated
    - name: Check dependencies for vulnerable packages
      run: dotnet list package --vulnerable --include-transitive

    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect "Code coverage"
      
    - name: Pack
      working-directory: src/Science.Cryptography.Ciphers
      run: dotnet pack --configuration Release --include-symbols --version-suffix "preview.${{ github.run_number }}"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: src/Science.Cryptography.Ciphers/bin/Release/*.nupkg

    - name: Pack
      working-directory: src/Science.Cryptography.Ciphers.Specialized
      run: dotnet pack --configuration Release --include-symbols --version-suffix "preview.${{ github.run_number }}"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: src/Science.Cryptography.Ciphers/bin/Release/*.nupkg

    - name: Pack
      working-directory: src/Science.Cryptography.Ciphers.Analysis
      run: dotnet pack --configuration Release --include-symbols --version-suffix "preview.${{ github.run_number }}"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: src/Science.Cryptography.Ciphers/bin/Release/*.nupkg

    - name: NuGet Authenticate
      run: nuget setapikey "${{ secrets.NUGET_API_KEY }}"
      
    - name: Push
      working-directory: src/Science.Cryptography.Ciphers
      run: nuget push bin/Release/*.nupkg
      
    - name: Push
      working-directory: src/Science.Cryptography.Ciphers.Specialized
      run: nuget push bin/Release/*.nupkg
      
    - name: Push
      working-directory: src/Science.Cryptography.Ciphers.Analysis
      run: nuget push bin/Release/*.nupkg
